### ISSUE TITLE
QS assumes mod location when loading files

### ISSUE THREAD

**Issue by taiwithers** [jn84/QualitySmash#8]
Mod (alpha 1.3) seems to search for assets assuming it's own location using an absolute path (see [SMAPI log](https://smapi.io/log/59debeacc1a747d789fbe51efb75a678)) and does not work if you have changed the folder name or placed it in a subfolder.

**Comment by jn84** [comment]
This issue is fixed in code, but I don't currently have the environment set up to release the changes. 

As I am not currently maintaining this repository, [NormanPCN's](https://github.com/NormanPCN/QualitySmash) fork is the currently recommended version. 

Any potential future versions released by me will be based on NormanPCN's fork.

I've updated the repo's description to reflect this.

Thank you
